name: gp_tutorial

dependencies:
  - python=3.7
  - ipython
  - ipywidgets
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - lxml
  - matplotlib
  - mkl-service
  - notebook
  - numpy=1.16
  - pandas
  - patsy
  - pip
  - pymc3
  - pydot
  - python-graphviz
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - theano
  - xlrd
  - pip:
    - arviz
